article/urls.py
from django.urls import path

from article import views

urlpatterns = [
    path('',views.ArticleListView.as_view(),name='list_article'),
    path('cat/<cat_title>', views.ArticleListView.as_view(), name='article_by_cat'),
    path('detail/<slug>', views.ArticleDetailView.as_view(), name='article_detail'),
    path('add_comment/',views.add_comment,name='add_comment')
]

eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
    path('product/',include('product.urls')),
    path('article/',include('article.urls')),
    path('contact-us/', include('contact_us.urls')),
    path('order/', include('order.urls')),
    path('user-panel/', include('user_panel.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('',views.home,name='home')
]

article/models.py
from django.db import models


# Create your models here.
# from jalali_date import datetime2jalali, date2jalali

from account.models import User


class ArticleCategoryModel(models.Model):
    parent = models.ForeignKey('ArticleCategoryModel',on_delete=models.CASCADE,verbose_name='دسته بندی والد',null=True,blank=True)
    title = models.CharField(max_length=200,verbose_name='عنوان')
    title_url = models.CharField(max_length=300,unique=True,verbose_name='عنوان در لینک')
    is_active = models.BooleanField(default=True,verbose_name='فعال / غیرفعال')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقالات'
        verbose_name_plural = 'دسته بندی های مقالات'

class Article(models.Model):
    title = models.CharField(max_length=300,verbose_name='عنوان')
    slug = models.SlugField(max_length=400,db_index=True,unique=True,allow_unicode=True,verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/article/',verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    description = models.TextField(verbose_name='توضیحات')
    is_active = models.BooleanField(verbose_name='حالت فعال / غیرفعال')
    categories = models.ManyToManyField(ArticleCategoryModel, verbose_name='دسته بندی ها')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='article',null=True,blank=True,editable=False)

    def __str__(self):
        return self.title

    # def get_jalali_data(self):
    #     return datetime2jalali(self.created_at)
    #
    # def get_jalali_data1(self):
    #     return self.get_jalali_data().strftime("%M:%H")
    # def get_jalali_time(self):
    #     return date2jalali(self.created_at)
    #
    # def get_jalali_time(self):
    #     return self.get_jalali_data().strftime("%H:%M")

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,verbose_name='مقاله',related_name='article')
    parent = models.ForeignKey('ArticleComment',on_delete=models.CASCADE,verbose_name='والد',related_name='parent_comment',null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر')
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField(verbose_name='متن کامنت')

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنتها'

    def __str__(self):
        return self.user.get_full_name()

article/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from sweetify import sweetify

from article.models import Article, ArticleComment, ArticleCategoryModel


class ArticleListView(ListView):
    model = Article
    template_name = 'article/article_list.html'
    paginate_by = 1
    context_object_name = 'article'
    # def get_queryset(self):
    #     qs = super(ArticleListView, self).get_queryset()
    #     qs=qs.objects.filter(is_active=True)
    #     return qs

    def get_queryset(self):
        qs = super(ArticleListView, self).get_queryset()
        cat_title = self.kwargs.get('cat_title')
        if cat_title:
            qs = qs.filter(categories__title_url__iexact=cat_title)
        return qs


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_detail.html'
    context_object_name = 'article'
    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data()
        article:Article = kwargs.get('object')
        comments = ArticleComment.objects.filter(parent=None, article=article).prefetch_related('parent_comment').order_by('-created_at')
        context['comments'] = comments
        context['comment_count'] = ArticleComment.objects.filter(article=article).count()
        return context

@login_required(login_url='/login')
def add_comment(request:HttpRequest):
    user = request.user
    article_id = request.GET.get('article_id')
    message = request.GET.get('message')
    parent = request.GET.get('parent_id')
    new_message = ArticleComment(article_id=article_id, text=message, user=user,parent_id=parent)
    new_message.save()
    context = {
        'comments' : ArticleComment.objects.filter(article_id=article_id).prefetch_related('parent_comment').order_by('-created_at'),
        'comment_count':ArticleComment.objects.filter(article_id=article_id).count()
    }
    return render(request, 'article/includes/message_box.html', context=context)


def right_side_component(request):
    main_category = ArticleCategoryModel.objects.filter(parent=None)
    context = {
        'main_category':main_category
    }
    return render(request,'article/right_side_component.html',context)

article/templates/article/article_detail.html
{% extends '_layout.html' %}
{% load render_partial %}
{% load thumbnail %}
{% load poll_extras %}
{% block title %}
    جزئیات مقالات
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">{{ article.title }}</h2>
                    <div class="single-blog-post">
                        <h3>{{ article.title }}</h3>
                        <div class="post-meta">
                            <ul>
                                <li><i class="fa fa-user"></i>{{ article.author }}</li>
                                <li><i class="fa fa-clock-o"></i>{{ article.created_at | to_jalali_time }}</li>
                                <li><i class="fa fa-calendar"></i>{{ article.created_at | to_jalali_time }}</li>
                            </ul>
                            <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                        </div>
                        <a href="">
                            <img src="images/blog/blog-one.jpg" alt="">
                        </a>
                        <p>{{ article.description }}</p>
                        <div class="pager-area">
                            <ul class="pager pull-left">
                                <li><a href="#">قبلی</a></li>
                                <li><a href="#">بعـدی</a></li>
                            </ul>
                        </div>
                    </div>
                </div><!--/blog-post-area-->

                {% if article.author %}
                    <div class="media commnets">
                        <a class="pull-right" href="#">
                            {% if article.author.avatar %}
                                {% thumbnail article.author.avatar "100x100" crop="center" quality=90 as im %}
                                    <img style="width: 100px;height: 100px" src="{{ im.url }}" class="media-object">
                                {% endthumbnail %}
                            {% else %}
                                <img style="width: 100px;height: 100px" class="media-object"
                                     src="/static/images/home/Tabs.png" alt="">
                            {% endif %}

                        </a>
                        <div class="media-body">

                            <h4 class="media-heading">نویسنده: {{ article.author }}</h4>
                            <p>{{ article.author.about_user }}</p>
                            <div class="blog-socials">
                                <ul>
                                    <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                    <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                    <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                    <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                                <a class="btn btn-primary" href="">سایـر مطالب نویسنده</a>
                            </div>

                        </div>
                    </div><!--Comments-->
                {% endif %}
                <div class="response-area" id="message_box">
                    <h2>نظرات ({{ comment_count }})</h2>
                    <ul class="media-list">
                        {% for comment in comments %}
                            <li class="media" id="parent_comment_{{ comment.id }}">
                                <a class="pull-right" href="#">
                                    {% if comment.user.avatar %}
                                        <img class="media-object" src="{{ comment.user.avatar.url }}" alt="">
                                    {% endif %}
                                </a>
                                <div class="media-body">
                                    <ul class="sinlge-post-meta">
                                        <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                        <li><i class="fa fa-clock-o"></i>{{ comment.created_at | to_jalali_time }}</li>
                                        <li><i class="fa fa-calendar"></i>{{ comment.created_at | to_jalali }}</li>
                                    </ul>
                                    <p>{{ comment.text }}</p>
                                    <a class="btn btn-primary" onclick="get_parent({{ comment.id }})"><i class="fa fa-reply"></i>پاسـخ</a>
                                </div>
                            </li>
                            {% for sub_comment in comment.parent_comment.all %}
                                <li class="media second-media">

                                    <a class="pull-right" href="#">
                                        {% if sub_comment.user.avatar %}
                                            <img class="media-object" src="{{ sub_comment.user.avatar.url }}" alt="">
                                        {% endif %}
                                    </a>
                                    <div class="media-body">
                                        <ul class="sinlge-post-meta">
                                            <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                            <li>
                                                <i class="fa fa-clock-o"></i>{{ sub_comment.created_at | to_jalali_time }}
                                            </li>
                                            <li><i class="fa fa-calendar"></i>{{ sub_comment.created_at | to_jalali }}
                                            </li>
                                        </ul>
                                        <p>{{ sub_comment.text }}</p>
                                    </div>
                                </li>
                            {% endfor %}
                        {% endfor %}

                    </ul>
                </div><!--/Response-area-->
                <div class="replay-box">
                    <div class="row" id="comment_box">
                        <h1>بخش ارسال نظرات</h1>
                        <div class="col-sm-12">
                            <div class="text-area">
                                <div class="blank-arrow">
                                    <label>متن پیام</label>
                                </div>
                                <input type="hidden" id="parent_id">
                                <textarea id="message" name="message" rows="11"></textarea>
                                <a class="btn btn-primary" onclick="add_comment({{ article.id }})">ارسـال نظـر</a>
                            </div>
                        </div>
                    </div>
                </div><!--/Repaly Box-->
            </div>
        {% render_partial 'article.views.right_side_component' %}
        </div>
    </div>
{% endblock %}

article/templates/article/article_list.html
{% extends '_layout.html' %}
{% load render_partial %}
{% load thumbnail %}
{% load poll_extras %}
{% block title %}
    مقالات
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">

            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">آخریـن اخبـار</h2>
                    {% for a in article %}
                        <div class="single-blog-post">
                            <h3>{{ a.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    <li><i class="fa fa-user"></i>{{ a.author }}</li>
                                    <li><i class="fa fa-calendar"></i>{{ a.created_at | to_jalali }}</li>
                                    <li><i class="fa fa-clock-o"></i>{{ a.created_at | to_jalali_time }}</li>
                                </ul>
                                <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                            </div>
                            <a href="">

                                {% thumbnail a.image "862x398" quality=90 crop='center' as im %}
                                   <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}
                            </a>
                            <p>{{ a.short_description }}</p>
                            <a class="btn btn-primary" href="{% url 'article_detail' slug=a.slug %}">ادامـه مطلب</a>
                        </div>
                    {% endfor %}

                    <div class="pagination-area">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for page_number in paginator %}
                                <li><a href="?page={{ page_number.number }}"
                                       class="{% if page_obj.number == page_number.number %} active{% endif %}">{{ page_number.number }}</a>
                                </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>

            {% render_partial 'article.views.right_side_component' %}

        </div>
    </div>
{% endblock %}

article/templates/article/right_side_component.html
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>دسته بندی مقالات</h2>
        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            {% for category in main_category %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            {% if category.articlecategorymodel_set.all %}
                                <a data-toggle="collapse" data-parent="#accordian" href="#{{ category.title_url }}">
                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                    {{ category.title }}
                                </a>
                            {% else %}
                                <a href="{% url 'article_by_cat' cat_title=category.title_url %}">
                                    {{ category.title }}
                                </a>
                            {% endif %}
                        </h4>
                    </div>
                    {% if category.articlecategorymodel_set.all %}
                        <div id="{{ category.title_url }}" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul>
                                    {% for sub_cat in category.articlecategorymodel_set.all %}
                                        <li><a href="{% url 'article_by_cat' cat_title=sub_cat.title_url %}">{{ sub_cat }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}

        </div><!--/category-productsr-->

        <div class="shipping text-center"><!--shipping-->
            <img src="/static/images/home/shipping.jpg" alt="">
        </div><!--/shipping-->

    </div>
</div>